import React from 'react';
import { useSelector  } from 'react-redux';

export default function MainContent() {
    const sidebar = useSelector(state => state.sidebar.value);
    const filterblock = useSelector(state => state.filterblock.value);

  return <main className={
      sidebar && filterblock 
      ? 'main filterMain sidebarMain' 
      : sidebar 
      ? 'main sidebarMain' 
      : filterblock 
      ? 'main filterMain' : 'main'
  }>
  <section className="main__wrapper">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed sem metus. Quisque quis dapibus orci. In sem augue, mollis rutrum tincidunt sollicitudin, bibendum vitae lectus. Nullam vel fringilla ex. Nullam vitae interdum purus. Integer hendrerit, eros non tempus bibendum, augue lorem sollicitudin dui, sit amet rutrum augue tellus vitae felis. Proin ut tellus rhoncus, dapibus dolor malesuada, bibendum lacus. Ut maximus mi at quam tristique, quis egestas odio aliquam. Phasellus scelerisque mattis lorem a egestas. Fusce nec ante nec nisl cursus vulputate. Phasellus in malesuada nulla.</p>
     <p>Duis egestas nulla at velit rutrum laoreet. Fusce id massa at eros posuere dignissim. Vestibulum ultrices tellus nec risus viverra molestie. Suspendisse vulputate fermentum est eget pellentesque. In sit amet interdum eros. Vestibulum pretium odio vel odio gravida, vel fringilla mi consectetur. Suspendisse dapibus auctor metus, a tincidunt nunc. Duis venenatis, quam a vehicula laoreet, lacus enim consequat mauris, in accumsan urna nisi in ipsum. Maecenas dictum augue libero, sit amet fermentum nibh blandit sit amet. Curabitur ligula felis, pharetra quis feugiat eu, molestie eget neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras volutpat dolor sed nisl mollis, sed blandit nunc efficitur.</p>
     <p>Vestibulum at tortor a augue fringilla mollis et vel odio. Sed nec facilisis velit. Etiam blandit, lectus vitae malesuada luctus, ipsum magna pellentesque ex, et ullamcorper felis turpis id justo. Aenean neque dolor, lacinia ut hendrerit non, consequat non eros. Nam iaculis egestas erat, sed cursus leo iaculis vel. Phasellus ornare est nec laoreet molestie. Nullam cursus orci quis augue condimentum euismod. Quisque ut pellentesque purus.</p>
    <p>Cras eleifend lectus ac leo bibendum fermentum. Maecenas fringilla nunc vel justo aliquet, ut semper nibh auctor. Sed in nisl nec ante mollis pellentesque ultricies quis dui. Fusce accumsan dictum libero, id pulvinar risus maximus vitae. Cras diam urna, lobortis in nunc id, cursus fermentum odio. Ut semper mi nec risus varius, quis pellentesque mi dictum. Duis a rhoncus nisi, in dictum purus. Pellentesque porta ex sed tellus gravida, et sodales est porttitor. Nullam varius massa eu nulla sollicitudin pulvinar. In at nulla quis nunc sodales tristique. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique blandit quam, at lacinia turpis vehicula vitae.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed sem metus. Quisque quis dapibus orci. In sem augue, mollis rutrum tincidunt sollicitudin, bibendum vitae lectus. Nullam vel fringilla ex. Nullam vitae interdum purus. Integer hendrerit, eros non tempus bibendum, augue lorem sollicitudin dui, sit amet rutrum augue tellus vitae felis. Proin ut tellus rhoncus, dapibus dolor malesuada, bibendum lacus. Ut maximus mi at quam tristique, quis egestas odio aliquam. Phasellus scelerisque mattis lorem a egestas. Fusce nec ante nec nisl cursus vulputate. Phasellus in malesuada nulla.</p>
     <p>Duis egestas nulla at velit rutrum laoreet. Fusce id massa at eros posuere dignissim. Vestibulum ultrices tellus nec risus viverra molestie. Suspendisse vulputate fermentum est eget pellentesque. In sit amet interdum eros. Vestibulum pretium odio vel odio gravida, vel fringilla mi consectetur. Suspendisse dapibus auctor metus, a tincidunt nunc. Duis venenatis, quam a vehicula laoreet, lacus enim consequat mauris, in accumsan urna nisi in ipsum. Maecenas dictum augue libero, sit amet fermentum nibh blandit sit amet. Curabitur ligula felis, pharetra quis feugiat eu, molestie eget neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras volutpat dolor sed nisl mollis, sed blandit nunc efficitur.</p>
     <p>Vestibulum at tortor a augue fringilla mollis et vel odio. Sed nec facilisis velit. Etiam blandit, lectus vitae malesuada luctus, ipsum magna pellentesque ex, et ullamcorper felis turpis id justo. Aenean neque dolor, lacinia ut hendrerit non, consequat non eros. Nam iaculis egestas erat, sed cursus leo iaculis vel. Phasellus ornare est nec laoreet molestie. Nullam cursus orci quis augue condimentum euismod. Quisque ut pellentesque purus.</p>
    <p>Cras eleifend lectus ac leo bibendum fermentum. Maecenas fringilla nunc vel justo aliquet, ut semper nibh auctor. Sed in nisl nec ante mollis pellentesque ultricies quis dui. Fusce accumsan dictum libero, id pulvinar risus maximus vitae. Cras diam urna, lobortis in nunc id, cursus fermentum odio. Ut semper mi nec risus varius, quis pellentesque mi dictum. Duis a rhoncus nisi, in dictum purus. Pellentesque porta ex sed tellus gravida, et sodales est porttitor. Nullam varius massa eu nulla sollicitudin pulvinar. In at nulla quis nunc sodales tristique. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tristique blandit quam, at lacinia turpis vehicula vitae.</p>
  
      </section></main>
}
